from pathlib import Path

from agentic_company.console.web.sql_backend import (
    _POSTGRES_POOLS,
    DatabaseSettings,
    _postgres_pool,
    _translate_sql,
    is_retryable_database_error,
    postgres_pool_bounds,
    retry_database_operation,
)


def test_database_settings_select_postgres_for_database_url():
    settings = DatabaseSettings(url="postgresql://user:pass@localhost:5432/app")

    assert settings.is_postgres
    assert settings.dialect == "postgres"


def test_database_settings_defaults_to_sqlite_for_path():
    settings = DatabaseSettings(sqlite_path=Path("data/console.db"))

    assert not settings.is_postgres
    assert settings.dialect == "sqlite"


def test_postgres_sql_translation_converts_identity_and_placeholders():
    sql = """
        CREATE TABLE IF NOT EXISTS runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL
        );
        SELECT * FROM runs WHERE name = ? AND note = '?';
    """

    translated = _translate_sql(sql)

    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in translated
    assert "name = %s" in translated
    assert "note = '?'" in translated


def test_postgres_pool_bounds_read_environment(monkeypatch):
    monkeypatch.setenv("AGENTIC_POSTGRES_POOL_MIN", "2")
    monkeypatch.setenv("AGENTIC_POSTGRES_POOL_MAX", "12")

    assert postgres_pool_bounds() == (2, 12)


def test_postgres_pool_bounds_reject_invalid_range(monkeypatch):
    monkeypatch.setenv("AGENTIC_POSTGRES_POOL_MIN", "5")
    monkeypatch.setenv("AGENTIC_POSTGRES_POOL_MAX", "2")

    try:
        postgres_pool_bounds()
    except ValueError as exc:
        assert "POOL_MAX" in str(exc)
    else:
        raise AssertionError("Expected invalid pool bounds to fail.")


def test_postgres_pool_is_reused_per_url(monkeypatch):
    monkeypatch.setenv("AGENTIC_POSTGRES_POOL_MIN", "1")
    monkeypatch.setenv("AGENTIC_POSTGRES_POOL_MAX", "3")
    _POSTGRES_POOLS.clear()

    first = _postgres_pool("postgresql://db/app", _FakePool, object())
    second = _postgres_pool("postgresql://db/app", _FakePool, object())

    assert first is second
    assert first.conninfo == "postgresql://db/app"
    assert first.min_size == 1
    assert first.max_size == 3
    assert first.opened

    _POSTGRES_POOLS.clear()


def test_retry_database_operation_retries_deadlock(monkeypatch):
    monkeypatch.setenv("AGENTIC_DATABASE_RETRY_ATTEMPTS", "3")
    monkeypatch.setenv("AGENTIC_DATABASE_RETRY_DELAY_SECONDS", "0")
    calls = {"count": 0}

    def operation():
        calls["count"] += 1
        if calls["count"] == 1:
            raise _FakeDatabaseError("deadlock detected", sqlstate="40P01")
        return "ok"

    assert retry_database_operation(operation) == "ok"
    assert calls["count"] == 2


def test_retry_database_operation_does_not_retry_contract_errors(monkeypatch):
    monkeypatch.setenv("AGENTIC_DATABASE_RETRY_ATTEMPTS", "3")
    calls = {"count": 0}

    def operation():
        calls["count"] += 1
        raise ValueError("contract failed")

    try:
        retry_database_operation(operation)
    except ValueError as exc:
        assert "contract failed" in str(exc)
    else:
        raise AssertionError("Expected contract error to fail without retry.")
    assert calls["count"] == 1


def test_retryable_database_error_detects_postgres_sqlstate():
    assert is_retryable_database_error(_FakeDatabaseError("boom", sqlstate="40P01"))


class _FakePool:
    def __init__(self, *, conninfo, min_size, max_size, kwargs, open):
        self.conninfo = conninfo
        self.min_size = min_size
        self.max_size = max_size
        self.kwargs = kwargs
        self.open_arg = open
        self.opened = False

    def open(self):
        self.opened = True


class _FakeDatabaseError(Exception):
    def __init__(self, message: str, *, sqlstate: str = "") -> None:
        super().__init__(message)
        self.sqlstate = sqlstate
