from pathlib import Path

from agentic_company.console.web.sql_backend import DatabaseSettings, _translate_sql


def test_database_settings_select_postgres_for_database_url():
    settings = DatabaseSettings(url="postgresql://user:pass@localhost:5432/app")

    assert settings.is_postgres
    assert settings.dialect == "postgres"


def test_database_settings_defaults_to_sqlite_for_path():
    settings = DatabaseSettings(sqlite_path=Path("data/console.db"))

    assert not settings.is_postgres
    assert settings.dialect == "sqlite"


def test_postgres_sql_translation_converts_identity_and_placeholders():
    sql = """
        CREATE TABLE IF NOT EXISTS runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL
        );
        SELECT * FROM runs WHERE name = ? AND note = '?';
    """

    translated = _translate_sql(sql)

    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in translated
    assert "name = %s" in translated
    assert "note = '?'" in translated
