"""Add user-scoped Codex auth metadata.

Revision ID: 20260620_0004
Revises: 20260614_0003
Create Date: 2026-06-20
"""

from __future__ import annotations

from alembic import op

revision = "20260620_0004"
down_revision = "20260614_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_codex_auth (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            auth_slot TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'disconnected',
            auth_mode TEXT NOT NULL DEFAULT '',
            last_checked_at TEXT NOT NULL DEFAULT '',
            last_refresh_at TEXT NOT NULL DEFAULT '',
            last_error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(user_id)
        );

        CREATE INDEX IF NOT EXISTS idx_user_codex_auth_status
            ON user_codex_auth(status, updated_at);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS user_codex_auth CASCADE;")
