"""Add Phase 1 runtime control and external board metadata.

Revision ID: 20260613_0002
Revises: 20260607_0001
Create Date: 2026-06-13
"""

from __future__ import annotations

from alembic import op

revision = "20260613_0002"
down_revision = "20260607_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE runs
            ADD COLUMN IF NOT EXISTS control_intent TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS control_intent_reason TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS control_intent_requested_at TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS reconcile_status TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS reconcile_reason TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS reconcile_backoff_until TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS reconcile_attempts INTEGER NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS reconciled_at TEXT NOT NULL DEFAULT '';

        CREATE TABLE IF NOT EXISTS work_system_connections (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,
            run_id INTEGER REFERENCES runs(id) ON DELETE CASCADE,
            system TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            base_url TEXT NOT NULL DEFAULT '',
            repository TEXT NOT NULL DEFAULT '',
            default_branch TEXT NOT NULL DEFAULT '',
            token_ref TEXT NOT NULL DEFAULT '',
            risk_mode TEXT NOT NULL DEFAULT 'assisted',
            status TEXT NOT NULL DEFAULT 'active',
            metadata TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS external_work_refs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            work_item_id TEXT NOT NULL DEFAULT '',
            connection_id INTEGER REFERENCES work_system_connections(id) ON DELETE CASCADE,
            system TEXT NOT NULL,
            external_type TEXT NOT NULL,
            idempotency_key TEXT NOT NULL DEFAULT '',
            source_event_id TEXT NOT NULL DEFAULT '',
            external_id TEXT NOT NULL DEFAULT '',
            external_url TEXT NOT NULL DEFAULT '',
            sync_status TEXT NOT NULL DEFAULT 'pending',
            last_sync_error TEXT NOT NULL DEFAULT '',
            last_synced_at TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(run_id, work_item_id, system, external_type, idempotency_key)
        );

        CREATE INDEX IF NOT EXISTS idx_runs_control_intent
            ON runs(control_intent, status, updated_at);
        CREATE INDEX IF NOT EXISTS idx_work_system_connections_run
            ON work_system_connections(run_id, system, status);
        CREATE INDEX IF NOT EXISTS idx_external_work_refs_run_item
            ON external_work_refs(run_id, work_item_id, system, external_type);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS external_work_refs CASCADE;
        DROP TABLE IF EXISTS work_system_connections CASCADE;

        ALTER TABLE runs
            DROP COLUMN IF EXISTS reconciled_at,
            DROP COLUMN IF EXISTS reconcile_attempts,
            DROP COLUMN IF EXISTS reconcile_backoff_until,
            DROP COLUMN IF EXISTS reconcile_reason,
            DROP COLUMN IF EXISTS reconcile_status,
            DROP COLUMN IF EXISTS control_intent_requested_at,
            DROP COLUMN IF EXISTS control_intent_reason,
            DROP COLUMN IF EXISTS control_intent;
        """
    )
