"""Add Phase 3 run modes, approvals, and team preset metadata.

Revision ID: 20260620_0005
Revises: 20260620_0004
Create Date: 2026-06-20
"""

from __future__ import annotations

from alembic import op

revision = "20260620_0005"
down_revision = "20260620_0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE runs
            ADD COLUMN IF NOT EXISTS run_mode TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS risk_mode TEXT NOT NULL DEFAULT 'assisted',
            ADD COLUMN IF NOT EXISTS team_preset TEXT NOT NULL DEFAULT 'standard',
            ADD COLUMN IF NOT EXISTS pause_reason TEXT NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS paused_at TEXT NOT NULL DEFAULT '';

        CREATE TABLE IF NOT EXISTS run_approvals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            gate_type TEXT NOT NULL,
            requested_action TEXT NOT NULL DEFAULT '',
            risk_summary TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'pending',
            requested_by TEXT NOT NULL DEFAULT '',
            decided_by TEXT NOT NULL DEFAULT '',
            decision_reason TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            decided_at TEXT NOT NULL DEFAULT '',
            updated_at TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_run_approvals_run_status
            ON run_approvals(run_id, status, created_at);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS run_approvals CASCADE;

        ALTER TABLE runs
            DROP COLUMN IF EXISTS paused_at,
            DROP COLUMN IF EXISTS pause_reason,
            DROP COLUMN IF EXISTS team_preset,
            DROP COLUMN IF EXISTS risk_mode,
            DROP COLUMN IF EXISTS run_mode;
        """
    )

