"""Initial PostgreSQL console schema.

Revision ID: 20260607_0001
Revises:
Create Date: 2026-06-07
"""

from __future__ import annotations

from alembic import op

revision = "20260607_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS schema_metadata (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            request_text TEXT NOT NULL DEFAULT '',
            mode TEXT NOT NULL DEFAULT 'simple_prototype',
            complexity TEXT NOT NULL DEFAULT 'simple',
            status TEXT NOT NULL DEFAULT 'draft',
            visibility TEXT NOT NULL DEFAULT 'private',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS runs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            run_uid TEXT NOT NULL UNIQUE,
            run_dir TEXT NOT NULL,
            target_project_dir TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'starting',
            mode TEXT NOT NULL DEFAULT 'simple_prototype',
            reasoning TEXT NOT NULL DEFAULT 'medium',
            generated_app_url TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS provider_credentials (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            provider TEXT NOT NULL,
            masked_value TEXT NOT NULL,
            encrypted_value TEXT NOT NULL DEFAULT '',
            storage_mode TEXT NOT NULL DEFAULT 'masked_only',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(user_id, provider)
        );

        CREATE TABLE IF NOT EXISTS artifact_metadata (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            artifact_id TEXT NOT NULL DEFAULT '',
            path TEXT NOT NULL,
            project_id INTEGER,
            work_item_id TEXT,
            label TEXT NOT NULL,
            agent TEXT NOT NULL,
            owner_agent TEXT NOT NULL DEFAULT '',
            artifact_type TEXT NOT NULL DEFAULT '',
            visibility TEXT NOT NULL DEFAULT 'business',
            storage_uri TEXT NOT NULL DEFAULT '',
            source_tool TEXT NOT NULL DEFAULT '',
            source_model TEXT NOT NULL DEFAULT '',
            external_refs TEXT NOT NULL DEFAULT '[]',
            metadata TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            UNIQUE(run_id, path)
        );

        CREATE TABLE IF NOT EXISTS artifact_contents (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            artifact_id TEXT NOT NULL,
            path TEXT NOT NULL,
            content_kind TEXT NOT NULL DEFAULT 'text',
            content_text TEXT NOT NULL DEFAULT '',
            content_json TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(run_id, artifact_id)
        );

        CREATE TABLE IF NOT EXISTS execution_requests (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            execution_id TEXT NOT NULL,
            agent_id TEXT NOT NULL,
            request_payload TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(run_id, execution_id)
        );

        CREATE TABLE IF NOT EXISTS agent_messages (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            message_id TEXT NOT NULL,
            from_agent TEXT NOT NULL,
            to_agent TEXT NOT NULL,
            intent TEXT NOT NULL,
            content TEXT NOT NULL DEFAULT '',
            artifact_refs TEXT NOT NULL DEFAULT '[]',
            correlation_id TEXT,
            parent_message_id TEXT,
            execution_id TEXT,
            parent_execution_id TEXT,
            status TEXT NOT NULL DEFAULT 'sent',
            created_at TEXT NOT NULL,
            UNIQUE(run_id, message_id)
        );

        CREATE TABLE IF NOT EXISTS delivery_state_snapshots (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            snapshot_id TEXT NOT NULL,
            stage TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT '',
            state_payload TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(run_id, snapshot_id)
        );

        CREATE TABLE IF NOT EXISTS run_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            runtime_run_id TEXT NOT NULL DEFAULT '',
            event_id TEXT NOT NULL,
            project_id INTEGER,
            work_item_id TEXT,
            agent_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT '',
            message TEXT NOT NULL DEFAULT '',
            artifact_ids TEXT NOT NULL DEFAULT '[]',
            external_refs TEXT NOT NULL DEFAULT '[]',
            data TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            UNIQUE(run_id, event_id)
        );

        CREATE TABLE IF NOT EXISTS tool_call_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            runtime_run_id TEXT NOT NULL DEFAULT '',
            event_id TEXT NOT NULL,
            work_item_id TEXT,
            agent_id TEXT NOT NULL,
            tool_name TEXT NOT NULL,
            tool_call_id TEXT NOT NULL,
            input_summary TEXT NOT NULL DEFAULT '{}',
            output_summary TEXT NOT NULL DEFAULT '{}',
            artifact_ids TEXT NOT NULL DEFAULT '[]',
            status TEXT NOT NULL DEFAULT '',
            failure_mode TEXT,
            duration_ms INTEGER,
            created_at TEXT NOT NULL,
            UNIQUE(run_id, event_id)
        );

        CREATE TABLE IF NOT EXISTS model_call_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            runtime_run_id TEXT NOT NULL DEFAULT '',
            event_id TEXT NOT NULL,
            agent_id TEXT NOT NULL,
            provider TEXT NOT NULL,
            model TEXT NOT NULL,
            purpose TEXT NOT NULL,
            prompt_ref TEXT NOT NULL DEFAULT '',
            input_tokens INTEGER,
            output_tokens INTEGER,
            estimated_cost_usd DOUBLE PRECISION,
            status TEXT NOT NULL DEFAULT '',
            duration_ms INTEGER,
            created_at TEXT NOT NULL,
            UNIQUE(run_id, event_id)
        );

        CREATE TABLE IF NOT EXISTS work_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            work_item_id TEXT NOT NULL,
            title TEXT NOT NULL,
            sprint_id TEXT NOT NULL DEFAULT '',
            delivery_order INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'todo',
            lane TEXT NOT NULL DEFAULT 'todo',
            owner_agent TEXT NOT NULL DEFAULT '',
            assigned_agent TEXT NOT NULL DEFAULT '',
            active INTEGER NOT NULL DEFAULT 0,
            source_refs TEXT NOT NULL DEFAULT '[]',
            artifact_ids TEXT NOT NULL DEFAULT '[]',
            blocker TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(run_id, work_item_id)
        );

        CREATE TABLE IF NOT EXISTS sprints (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            sprint_id TEXT NOT NULL,
            title TEXT NOT NULL DEFAULT '',
            delivery_order INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'planned',
            is_final INTEGER NOT NULL DEFAULT 0,
            source_refs TEXT NOT NULL DEFAULT '[]',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(run_id, sprint_id)
        );

        CREATE TABLE IF NOT EXISTS work_item_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            event_id TEXT NOT NULL,
            work_item_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            from_status TEXT NOT NULL DEFAULT '',
            to_status TEXT NOT NULL DEFAULT '',
            from_owner TEXT NOT NULL DEFAULT '',
            to_owner TEXT NOT NULL DEFAULT '',
            agent_id TEXT NOT NULL DEFAULT '',
            tool_name TEXT NOT NULL DEFAULT '',
            tool_call_id TEXT NOT NULL DEFAULT '',
            message TEXT NOT NULL DEFAULT '',
            visibility TEXT NOT NULL DEFAULT 'user',
            created_at TEXT NOT NULL,
            UNIQUE(run_id, event_id)
        );

        CREATE TABLE IF NOT EXISTS activity_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            event_id TEXT NOT NULL,
            work_item_id TEXT NOT NULL,
            owner_agent TEXT NOT NULL DEFAULT '',
            agent_id TEXT NOT NULL DEFAULT '',
            tool_name TEXT NOT NULL DEFAULT '',
            message TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT '',
            artifact_ids TEXT NOT NULL DEFAULT '[]',
            visibility TEXT NOT NULL DEFAULT 'user',
            created_at TEXT NOT NULL,
            UNIQUE(run_id, event_id)
        );

        CREATE TABLE IF NOT EXISTS raw_log_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            work_item_id TEXT,
            sprint_id TEXT NOT NULL DEFAULT '',
            agent_id TEXT NOT NULL,
            tool_name TEXT NOT NULL DEFAULT '',
            tool_call_id TEXT NOT NULL DEFAULT '',
            seq INTEGER NOT NULL,
            level TEXT NOT NULL DEFAULT '',
            stream TEXT NOT NULL DEFAULT '',
            message TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(run_id, agent_id, tool_call_id, seq)
        );

        CREATE TABLE IF NOT EXISTS console_processes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            process_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT '',
            thread_name TEXT NOT NULL DEFAULT '',
            env_keys TEXT NOT NULL DEFAULT '[]',
            stop_requested_at TEXT NOT NULL DEFAULT '',
            error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(run_id, process_name)
        );

        CREATE INDEX IF NOT EXISTS idx_runs_project_created
            ON runs(project_id, created_at DESC, id DESC);
        CREATE INDEX IF NOT EXISTS idx_projects_owner_updated
            ON projects(owner_user_id, visibility, updated_at DESC, id DESC);
        CREATE INDEX IF NOT EXISTS idx_work_items_run_sprint_order
            ON work_items(run_id, sprint_id, delivery_order, work_item_id);
        CREATE INDEX IF NOT EXISTS idx_work_items_run_status
            ON work_items(run_id, status, active);
        CREATE INDEX IF NOT EXISTS idx_sprints_run_order
            ON sprints(run_id, delivery_order, sprint_id);
        CREATE INDEX IF NOT EXISTS idx_work_item_events_run_item_created
            ON work_item_events(run_id, work_item_id, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_activity_events_run_item_created
            ON activity_events(run_id, work_item_id, visibility, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_artifact_metadata_run_item_visibility
            ON artifact_metadata(run_id, work_item_id, visibility, created_at);
        CREATE INDEX IF NOT EXISTS idx_tool_call_events_run_item_created
            ON tool_call_events(run_id, work_item_id, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_run_events_run_item_created
            ON run_events(run_id, work_item_id, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_model_call_events_run_agent_created
            ON model_call_events(run_id, agent_id, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_raw_log_events_run_item_seq
            ON raw_log_events(run_id, work_item_id, id);
        CREATE INDEX IF NOT EXISTS idx_raw_log_events_run_agent_seq
            ON raw_log_events(run_id, agent_id, id);
        CREATE INDEX IF NOT EXISTS idx_agent_messages_run_to_created
            ON agent_messages(run_id, to_agent, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_agent_messages_run_correlation
            ON agent_messages(run_id, correlation_id, created_at, id);
        CREATE INDEX IF NOT EXISTS idx_console_processes_run_name
            ON console_processes(run_id, process_name);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS console_processes CASCADE;
        DROP TABLE IF EXISTS raw_log_events CASCADE;
        DROP TABLE IF EXISTS activity_events CASCADE;
        DROP TABLE IF EXISTS work_item_events CASCADE;
        DROP TABLE IF EXISTS sprints CASCADE;
        DROP TABLE IF EXISTS work_items CASCADE;
        DROP TABLE IF EXISTS model_call_events CASCADE;
        DROP TABLE IF EXISTS tool_call_events CASCADE;
        DROP TABLE IF EXISTS run_events CASCADE;
        DROP TABLE IF EXISTS delivery_state_snapshots CASCADE;
        DROP TABLE IF EXISTS agent_messages CASCADE;
        DROP TABLE IF EXISTS execution_requests CASCADE;
        DROP TABLE IF EXISTS artifact_contents CASCADE;
        DROP TABLE IF EXISTS artifact_metadata CASCADE;
        DROP TABLE IF EXISTS provider_credentials CASCADE;
        DROP TABLE IF EXISTS runs CASCADE;
        DROP TABLE IF EXISTS projects CASCADE;
        DROP TABLE IF EXISTS sessions CASCADE;
        DROP TABLE IF EXISTS schema_metadata CASCADE;
        DROP TABLE IF EXISTS users CASCADE;
        """
    )
